### ISSUE TITLE
Build fails on Node 12.13.0

### ISSUE THREAD

**Issue by pheyvaer** [RubenVerborgh/HDT-Node#42] opened 2019-11-28 15:54 UTC
Building the code on Node 12.13.0 fails, while it still works on 10.17.0.

**Comment by RubenVerborgh** [comment] 2019-11-28 15:55
New version of NAN is likely to help.

**Comment by mielvds** [comment] 2019-12-03 10:12
I can confirm the issue. Do we bump the nan version because this also blocks building the LDF server for instance.

**Comment by rubensworks** [comment] 2019-12-03 10:13
This issue appears to be a duplicate of #41.

**Comment by mielvds** [comment] 2019-12-04 08:52
also fixed by #43

**Closed** 2019-12-20 10:12 UTC
